server:
  port: 8080

spring:
  application:
    name: sample-service
  config:
    import: optional:configserver:http://localhost:8888

logging:
  level:
    org.springframework.cloud: INFO

---
spring:
  config:
    activate:
      on-profile: cloud

message: Hello Cloud!
